### ISSUE TITLE
Simplify GitTorrent

### ISSUE THREAD

**Issue by pickfire** [cjb/GitTorrent#17]
I think it is easier for users to use `git clone gitt@sjb/something` rather than `git clone gittorrent://sjb/something`. Is it better that way? And what about `gt`?

**Comment by cjb** [comment]
If everyone grabbed the two-letter version of their custom protocol it'd get messed up.  But I agree it's annoyingly long.  I guess I don't like `gitt` or `gt` though.  :)

**Comment by pickfire** [comment]
I think that not everybody like to type `gittorrent` and `gittorrend` a few times just to set-up a git repository for gittorrent. Maybe think for a shorter and worthy name as the project is still new.

**Comment by nesk** [comment]
Seriously, is it really _that_ hard to write 7 more characters compare to what you usually have to write? A shorter alias can be created latter, I don't think this what @cjb wants to work on as a priority.

**Comment by pickfire** [comment]
Thanks. I don't think that is so hard to write. Closing.

**Comment by cjb** [comment]
Just a few thoughts:  I *am* open to a shorter alias, I just don't like any of the ones I can think of, they aren't descriptive enough.  And it's fine to file issues that are not highest priority -- I'm not the only person who can work on them!
