### ISSUE TITLE
Why GitTorrent?

### ISSUE THREAD

**Issue by ThreaT** [cjb/GitTorrent#31]
Perhaps more of a wiki FAQ - Shouldn't all websites be decentralized? I would think that this goes beyond the scope of GitHub only, more like Web 3.0. Couldn't this be achieved using WebRTC? What are the main benefits for connecting this to the blockchain? It would be useful to have something like this to develop new web apps as well...

**Comment by cjb** [comment]
Sure, we could start an FAQ.

> Couldn't this be achieved using WebRTC?

Not easily; WebRTC needs signaling (offer/answer exchange) before peers can talk to each other, which introduces centralization.  Once we have a DHT that works with WebRTC we could try it out.

> What are the main benefits for connecting this to the blockchain?

Usernames.  (.. that work like GitHub's; a single shared namespace.)

**Comment by cjb** [comment]
> WebRTC

Did you mean in browsers rather than Node, btw?  The reason I haven't pushed trying to get this to work in browsers (other than the lack of WebRTC DHT) is that I don't know what I would do with a Git repo that I cloned into a browser.

**Comment by Liamsi** [comment]
@ThreaT  there is startup in Scotland trying to build something where you can develop (web)apps on: http://maidsafe.net/ 
They do not use blockchain technology (at least not for the network part) nor webrtc. But I did not have the time to thoroughly look through their (papers)[http://maidsafe.net/documents]
@cjb Thanks for this great project!

**Comment by ThreaT** [comment]
@Liamsi Good call. I have been following maidsafe for some time as well. @cjb Have you considered building this using maidsafe?

**Comment by cjb** [comment]
I don't know much about Maidsafe, Ethereum or IPFS and all seem like they have relevant ideas.  If anyone knows more about them and can explain how the GitTorrent design might fit together with them I'd be happy to chat about it (perhaps on IRC).

**Comment by ralphtheninja** [comment]
cc @ioptio

**Comment by ThreaT** [comment]
@cjb 

> The reason I haven't pushed trying to get this to work in browsers (other than the lack of WebRTC DHT) is that I don't know what I would do with a Git repo that I cloned into a browser.

One scenario could be the general lack of community integration on GitHub. If I want to draw attention to a particular repository or pay to get work done on an open source repository, I can't really flag the repository for the community to find.

**Comment by cjb** [comment]
Ah, but you don't need to have cloned the repository itself into the browser to do that.

It sounds like this use case could live on a Secure Scuttlebutt stream if we end up using that to host issues and pull requests.

**Comment by ThreaT** [comment]
cc @jasonrudolph

**Comment by sg-s** [comment]
perhaps add a section comparing and contrasting to [gitchain](http://gitchain.org/)? thanks.

**Comment by anarcat** [comment]
it'd be great to have a FAQ.mdwn in the repo. :)

> Shouldn't all websites be decentralized?

You're looking for http://ipfs.io/ for that, really. This is just about git. :)

**Comment by waldyrious** [comment]
> perhaps add a section comparing and contrasting to gitchain?

Also https://code.google.com/p/gittorrent/

**Comment by dcousens** [comment]
Tag as 'question' and close?

**Comment by cjb** [comment]
Sure.

**Comment by waldyrious** [comment]
Can someone summarize the Q&A from this thread in the [wiki FAQ](../wiki)? I'm not sure I am qualified to do it due to my superficial understanding of the concepts involved.
