### ISSUE TITLE
Is this related to https://code.google.com/p/gittorrent/ in any way?

### ISSUE THREAD

**Issue by tv42** [cjb/GitTorrent#53]
Once more, with a clickable link: https://code.google.com/p/gittorrent/

**Comment by cjb** [comment]
@tv42 No, not meaningfully related -- I asked the developers of that project if I could reuse their name and they said sure.  Their design doesn't use a Distributed Hash Table at all (I think their project maybe predates BitTorrent's DHT!), whereas one is central to this project's design, so there's little in common other than the general idea of combining Git and BitTorrent.

**Comment by tv42** [comment]
That's what it looked like, thanks. Take this as a FAQ suggestion.

**Comment by dcousens** [comment]
Close?

**Comment by cjb** [comment]
Sure.

**Comment by waldyrious** [comment]
I added this as the first question in a [wiki FAQ](../wiki).

**Comment by cjb** [comment]
@waldyrious Nice, thanks very much! Feel free to keep adding more.  :)
