### ISSUE TITLE
Cannot clone repo

### ISSUE THREAD

**Issue by pditommaso** [cjb/GitTorrent#64]
I'm playing with gittorrent. Trying to clone a repository it hung reporting the following output: 

   	$ git clone gittorrent://github.com/cbcrg/ampa-nf/
	Cloning into 'ampa-nf'...
	Okay, we want to get HEAD: 3c2bce5f758585fe3e0bf23df77f6f53853bc3b8
	Okay, we want to get master: 3c2bce5f758585fe3e0bf23df77f6f53853bc3b8
	Okay, we want to get tags/v1.0: ca3d597ea2149978840d5c7a43e3149079fab184

Any clue what it could be the problem?

**Comment by cjb** [comment]
@pditommaso I think it just means that no-one's hosting that repo on gittorrent.  #5 handles falling back to talking to github directly in the case where no-one's seeding.  (Feel free to pitch in!)

**Comment by pditommaso** [comment]
I see. It makes sense, however I'm still confused. 

How I can manage to host that repo on gittorrent? I've tried to clone it locally and then to run the `gittorrentd` daemon, as show below: 

	$ git clone git@github.com:cbcrg/ampa-nf.git
	$ touch ampa-nf/.git/git-daemon-export-ok
	$ gittorrentd
	in repo ampa-nf/.git/git-daemon-export-ok
	ampa-nf/.git/
	Announcing 3c2bce5f758585fe3e0bf23df77f6f53853bc3b8 for HEAD on repo ampa-nf/.git/
	{"repositories":{"ampa-nf":{"HEAD":"3c2bce5f758585fe3e0bf23df77f6f53853bc3b8","refs/heads/master":"3c2bce5f758585fe3e0bf23df77f6f53853bc3b8"}}}
	errors= []


However I'm still unable to clone it by using the gittorrent protocol. What I'm missing ?

**Comment by cjb** [comment]
That's surprising, it should work, perhaps a firewall problem?

**Comment by pditommaso** [comment]
Yes, I think it was the firewall. Trying on another machine it worked.  Thanks.

**Comment by alexgleason** [comment]
Running into this problem too. Here's the output from gittorrentd

```
alex@Starman:~/GitTorrent$ gittorrentd 
in repo pig-latin/.git/git-daemon-export-ok
pig-latin/.git/
Announcing f29e764924c016d20db226078f3dcd3d901e7de9 for HEAD on repo pig-latin/.git/
{"repositories":{"pig-latin":{"HEAD":"f29e764924c016d20db226078f3dcd3d901e7de9","refs/heads/master":"f29e764924c016d20db226078f3dcd3d901e7de9"}}}
errors= [ { [Error: 203 invalid token] address: '41.100.181.230:10219' },
  { [Error: 203 invalid token] address: '123.18.113.210:21136' },
  { [Error: 204 Unknown query type.] address: '50.81.81.196:6881' },
  { [Error: query timed out] address: '95.134.168.96:35691' },
  { [Error: query timed out] address: '183.82.243.49:58105' },
  { [Error: query timed out] address: '109.60.193.167:62529' },
  { [Error: query timed out] address: '191.177.186.254:5724' },
  { [Error: query timed out] address: '143.248.11.25:27798' },
  { [Error: query timed out] address: '177.135.62.202:18800' },
  { [Error: query timed out] address: '1.253.134.226:45682' },
  { [Error: query timed out] address: '177.133.50.163:41846' },
  { [Error: query timed out] address: '187.207.27.100:12026' },
  { [Error: query timed out] address: '75.158.30.194:20165' },
  { [Error: query timed out] address: '82.27.165.143:52439' },
  { [Error: query timed out] address: '59.97.60.219:15609' },
  { [Error: query timed out] address: '173.60.69.97:80' },
  { [Error: query timed out] address: '117.197.178.163:22236' },
  { [Error: query timed out] address: '83.85.167.138:34478' },
  { [Error: query timed out] address: '145.53.184.204:60286' },
  { [Error: query timed out] address: '185.74.221.102:1049' } ]
hash= 2a0d643de89314ec56f749a851a3807edbdac6b5
```

Any ideas? Thanks!

**Comment by alexpear** [comment]
If it's a firewall problem, which process should we tell the firewall to allow? git?
