### ISSUE TITLE
Clone hangs forever for self-hosted repo

### ISSUE THREAD

**Issue by alexpear** [cjb/GitTorrent#78]
I haven't been able to clone served-by-gittorrentd repos on any of 3 machines (OSX, ubuntu, ubuntu). For one thing, do we want a timeout?

Things i've tried: 
- Firewall permissions for gittorrentd
- Different LANs and VPNs
- gittorrent://[hash of daemon]/[reponame]
- gittorrent://[hash of repo]/[reponame]

etc

Any suggestions for how to make this work would be appreciated.

**Comment by cjb** [comment]
A timeout would be great, feel free to PR :)

I'll check it out when I get a sec, might be my fault.

**Comment by cjb** [comment]
Hi!  Okay, I've restarted the DHT server and checked that:

```
git clone gittorrent://github.com/cjb/gittorrent
git clone gittorrent://81e24205d4bac8496d3e13282c90ead5045f09ea/gittorrent
```

both work fine.  Feel free to send me a log if you'd like help debugging your stuff.

**Comment by alexpear** [comment]
It works for me now! I don't think i changed anything. That DHT server reboot might have been necessary. 
Thanks.
